cache: bundler
sudo: false
bundler_args: ""
rvm:
  - 2.5
gemfile:
  - gemfiles/rails6.0.gemfile
before_install: gem i matching_bundle && matching_bundle install
script: matching_bundle exec rake spec spec/soft_deletion_spec.rb:685