cache: bundler
sudo: false
bundler_args: ""
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
branches:
  only: master
before_install: gem i matching_bundle && matching_bundle install
script: matching_bundle exec rake spec
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails4.2.gemfile
